/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  PurchaseOrderHeader as PrismaPurchaseOrderHeader,
} from "@prisma/client";

export class PurchaseOrderHeaderServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.PurchaseOrderHeaderCountArgs, "select">
  ): Promise<number> {
    return this.prisma.purchaseOrderHeader.count(args);
  }

  async purchaseOrderHeaders(
    args: Prisma.PurchaseOrderHeaderFindManyArgs
  ): Promise<PrismaPurchaseOrderHeader[]> {
    return this.prisma.purchaseOrderHeader.findMany(args);
  }
  async purchaseOrderHeader(
    args: Prisma.PurchaseOrderHeaderFindUniqueArgs
  ): Promise<PrismaPurchaseOrderHeader | null> {
    return this.prisma.purchaseOrderHeader.findUnique(args);
  }
  async createPurchaseOrderHeader(
    args: Prisma.PurchaseOrderHeaderCreateArgs
  ): Promise<PrismaPurchaseOrderHeader> {
    return this.prisma.purchaseOrderHeader.create(args);
  }
  async updatePurchaseOrderHeader(
    args: Prisma.PurchaseOrderHeaderUpdateArgs
  ): Promise<PrismaPurchaseOrderHeader> {
    return this.prisma.purchaseOrderHeader.update(args);
  }
  async deletePurchaseOrderHeader(
    args: Prisma.PurchaseOrderHeaderDeleteArgs
  ): Promise<PrismaPurchaseOrderHeader> {
    return this.prisma.purchaseOrderHeader.delete(args);
  }
}
